spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edutrack
    username: ${DB_USER:edutrack_user}
    password: ${DB_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: update   # Hibernate crea y actualiza el schema automáticamente
    show-sql: true       # útil durante el desarrollo
    properties:
      hibernate.format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:GfyA0J3ATRphLxXWFnPW2QzigcJ+27xBMhQxkpBPyD7gWQXfHD/1QirOcyJaXLqQLXhaUKxhzvhnKXBO8LrHBgvjWYziMa7kGDZmuB4iplre27OHeuQlgsMrQUHjCRWasrQRsq+cxC0SuGBSM6j+r3A8sDSRCnPCCHr98ds3bPlVn25gEpSDQGclpSnTYEU2cCkwQeH7DZjhLabDsjhGIyN/y1RE+voKZ9szZ88qWIQGbC8Kae96lDoH9ieUaHmmSb1dRJ+SBLfpx2QWY2wJ2duao6afggsHtaKr6Lg/Ck3YtQrrZLAKIge1cEPF9XAHjEOFtv8hJSRfnXRwlYbnkg==}
    access-expiration: 3600000     # 1 hora en ms
    refresh-expiration: 604800000  # 7 días en ms

springdoc:
  swagger-ui.path: /swagger-ui.html
