spring:
  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.frutmhwyvhswxljkgyhi
    password: strongP#a<>ord
  jpa:
    hibernate:
      ddl-auto: update   # Hibernate crea y actualiza el schema automáticamente
    show-sql: true       # útil durante el desarrollo
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:clave_local_de_desarrollo_minimo_256_bits}
    access-expiration: 3600000     # 1 hora en ms
    refresh-expiration: 604800000  # 7 días en ms

springdoc:
  swagger-ui.path: /swagger-ui.html
